[repository]
# Must be in lower-case letters
REGISTRY_NAME = "nathan-vm"

# The name of this Pieces repository
REPOSITORY_NAME = "openai_api_pieces"
REPOSITORY_LABEL = "OpenAI Domino Pieces"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.7.3"

